name: CI for FastAPI Sum App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-lint-build:
    runs-on: ubuntu-latest
    name: Run Tests, Lint, and Docker Build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

    - name: Run tests with pytest
      run: |
        pytest

    - name: Run flake8 linting
      run: |
        pip install flake8
        flake8 app

    - name: Build Docker Image
      run: |
        docker build -t fastapi-sum-app .
